version: '3.9'
services:
  db:
    image: postgres:14.3
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - instagram_app_network
  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - instagram_app_network
  app:
    container_name: instagram-app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/var/app
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=development
    depends_on:
      - redis
    links:
      - redis
    stdin_open: true
    tty: true
    networks:
      - instagram_app_network

networks:
  instagram_app_network:
